export const news = [
  {
    id: "1",
    name: "",
    country: "kaz",
    img: "images/uzbekistan/resource/gallery_kazakhstan_2_325x300.webp",
  },
  {
    id: "1",
    name: "",
    country: "kaz",
    img: "images/uzbekistan/news/kaz1.jpg",
  },
  {
    id: "2",
    name: "",
    country: "kaz",
    img: "images/uzbekistan/news/kaz2.jpg",
  },
  {
    id: "3",
    name: "",
    country: "kaz",
    img: "images/uzbekistan/news/kaz3.jpg",
  },
  {
    id: "4",
    name: "",
    country: "kaz",
    img: "images/uzbekistan/news/kaz4.jpg",
  },
  {
    id: "5",
    name: "",
    country: "kaz",
    img: "images/uzbekistan/news/kaz5.jpg",
  },
  {
    id: "6",
    name: "",
    country: "kaz",
    img: "images/uzbekistan/news/kaz6.jpg",
  },
  {
    id: "7",
    name: "",
    country: "kaz",
    img: "images/uzbekistan/news/kaz7.jpg",
  },
  {
    id: "8",
    name: "",
    country: "kaz",
    img: "images/uzbekistan/news/kaz8.jpg",
  },
  {
    id: "9",
    name: "",
    country: "kaz",
    img: "images/uzbekistan/news/kaz9.jpg",
  },
  {
    id: "10",
    name: "",
    country: "kaz",
    img: "images/uzbekistan/news/kaz10.jpg",
  },
  {
    id: "11",
    name: "",
    country: "kyr",
    img: "images/uzbekistan/news/kyr1.jpg",
  },
  {
    id: "12",
    name: "",
    country: "kyr",
    img: "images/uzbekistan/news/kyr2.jpg",
  },
  {
    id: "13",
    name: "",
    country: "kyr",
    img: "images/uzbekistan/news/kyr3.jpg",
  },
  {
    id: "14",
    name: "",
    country: "kyr",
    img: "images/uzbekistan/news/kyr4.jpg",
  },
  {
    id: "15",
    name: "",
    country: "kyr",
    img: "images/uzbekistan/news/kyr5.jpg",
  },
  {
    id: "151",
    name: "",
    country: "kyr",
    img: "images/uzbekistan/news/kyr6.jpg",
  },
  {
    id: "151",
    name: "video",
    country: "kyr",
    img: "images/uzbekistan/news/kyr8.mp4",
  },
  {
    id: "16",
    name: "",
    country: "uzb",
    img: "images/uzbekistan/resource/gallery_uzbekistan_1_675x300.webp",
  },
  {
    id: "16",
    name: "",
    country: "uzb",
    img: "images/uzbekistan/resource/gallery_uzbekistan_2_325x300.webp",
  },
  {
    id: "16",
    name: "",
    country: "uzb",
    img: "images/uzbekistan/resource/gallery_uzbekistan_3_325x300.webp",
  },
  {
    id: "16",
    name: "",
    country: "uzb",
    img: "images/uzbekistan/news/uzb1.jpg",
  },
  {
    id: "17",
    name: "",
    country: "uzb",
    img: "images/uzbekistan/news/uzb2.jpg",
  },
  {
    id: "18",
    name: "",
    country: "uzb",
    img: "images/uzbekistan/news/uzb3.jpg",
  },
  {
    id: "19",
    name: "",
    country: "uzb",
    img: "images/uzbekistan/news/uzb4.jpg",
  },
  {
    id: "20",
    name: "",
    country: "uzb",
    img: "images/uzbekistan/news/uzb5.jpg",
  },
  {
    id: "21",
    name: "",
    country: "uzb",
    img: "images/uzbekistan/news/uzb6.jpg",
  },
  {
	  id: "22",
	  name: "",
	  country: "uzb",
	  img: "images/uzbekistan/news/uzb7.jpg",
	},
	{
    id: "23",
    name: "",
    country: "uzb",
    img: "images/uzbekistan/news/uzb8.jpg",
  },
  {
    id: "24",
    name: "",
    country: "uzb",
    img: "images/uzbekistan/news/uzb9.jpg",
},
{
	id: "25",
    name: "",
    country: "uzb",
    img: "images/uzbekistan/news/uzb10.jpg",
},
{
  id: "29",
  name: "video",
  country: "uzb",
  img: "images/uzbekistan/news/video.mp4",
},
{
	id: "26",
    name: "",
    country: "taj",
    img: "images/uzbekistan/resource/gallery_uzbekistan_4_325x300.webp",
},
  {
    id: "26",
    name: "",
    country: "taj",
    img: "images/uzbekistan/resource/gallery_tajikistan_2_675x300.webp",
  },
  {
    id: "26",
    name: "",
    country: "taj",
    img: "images/uzbekistan/news/taj1.jpg",
  },
  {
    id: "27",
    name: "",
    country: "taj",
    img: "images/uzbekistan/news/taj2.jpg",
  },
  {
    id: "28",
    name: "",
    country: "taj",
    img: "images/uzbekistan/news/taj3.jpg",
  },
];
